# Generated by Django 5.1 on 2024-10-20 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaExcelencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta', models.CharField(max_length=30, unique=True)),
                ('lugar', models.CharField(max_length=50)),
                ('fechadefensa', models.DateField(default=django.utils.timezone.now)),
                ('horainicio', models.TimeField()),
                ('horafin', models.TimeField()),
                ('notatotal', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.carrera')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_exc_estudiante', to=settings.AUTH_USER_MODEL)),
                ('jurado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_exc_jurado_1', to=settings.AUTH_USER_MODEL)),
                ('jurado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_exc_jurado_2', to=settings.AUTH_USER_MODEL)),
                ('jurado_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_exc_jurado_3', to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad')),
                ('perperiodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.periodo')),
                ('presidenteacta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_presidente_Asi', to=settings.AUTH_USER_MODEL)),
                ('secretario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_exc_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acta Excelencia',
                'verbose_name_plural': 'Actas Defensa Excelencia',
            },
        ),
    ]
