# Generated by Django 5.1 on 2024-10-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0003_alter_repositoriotitulados_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoriotitulados',
            name='titulo',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
