# Generated by Django 5.1 on 2024-10-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0004_alter_repositoriotitulados_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='invcientifica',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='invcientifica',
            name='user_dos',
        ),
    ]
