# Generated by Django 5.1 on 2024-10-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0005_remove_docente_dni_remove_estudiante_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilproyecto',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='perfilproyecto',
            name='user_dos',
        ),
    ]
