# Generated by Django 5.1 on 2024-10-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0006_remove_perfilproyecto_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilitarproyectofinal',
            name='estudiante_dos',
        ),
        migrations.RemoveField(
            model_name='proyectofinal',
            name='estudiante_dos',
        ),
        migrations.RemoveField(
            model_name='repositoriotitulados',
            name='estudiante_dos',
        ),
    ]
