# Generated by Django 5.1 on 2024-10-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0007_remove_habilitarproyectofinal_estudiante_dos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaexcelencia',
            name='docrespaldo',
            field=models.FileField(blank=True, null=True, upload_to='documento/actaexcelencia', verbose_name='Agregar Documentacion'),
        ),
        migrations.AddField(
            model_name='actaprivada',
            name='docrespaldo',
            field=models.FileField(blank=True, null=True, upload_to='documento/actaprivada', verbose_name='Agregar Documentacion'),
        ),
        migrations.AddField(
            model_name='actaproyectoperfil',
            name='docrespaldo',
            field=models.FileField(blank=True, null=True, upload_to='documento/actaperfil', verbose_name='Agregar Documentacion'),
        ),
        migrations.AddField(
            model_name='actapublica',
            name='docrespaldo',
            field=models.FileField(blank=True, null=True, upload_to='documento/actapublica', verbose_name='Agregar Documentacion'),
        ),
        migrations.AddField(
            model_name='actaviadiplomado',
            name='docrespaldo',
            field=models.FileField(blank=True, null=True, upload_to='documento/actaviadiplomado', verbose_name='Agregar Documentacion'),
        ),
    ]
