# Generated by Django 5.1 on 2024-10-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0009_alter_actaproyectoperfil_docrespaldo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actaproyectoperfil',
            options={'verbose_name': 'Acta Perfil', 'verbose_name_plural': 'Actas Perfil'},
        ),
        migrations.RemoveField(
            model_name='actaviadiplomado',
            name='estudiante_uno',
        ),
    ]
