# Generated by Django 5.1 on 2024-10-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0011_area_materia_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='Espacio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
