# Generated by Django 5.1 on 2024-10-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0013_carrera_espacio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultad',
            name='Espacio',
        ),
    ]
