# Generated by Django 5.1 on 2024-10-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0014_remove_facultad_espacio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='Espacio',
        ),
    ]
