# Generated by Django 5.1 on 2024-10-28 18:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0015_remove_carrera_espacio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta', models.CharField(max_length=30, unique=True)),
                ('lugar', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=250)),
                ('espacio', models.CharField(max_length=250)),
                ('fechadefensa', models.DateField(default=django.utils.timezone.now)),
                ('horainicio', models.TimeField()),
                ('horafin', models.TimeField()),
                ('nota', models.IntegerField()),
                ('lugar_1', models.CharField(max_length=50)),
                ('campus_1', models.CharField(max_length=250)),
                ('espacio_1', models.CharField(max_length=250)),
                ('fechadefensa_1', models.DateField(default=django.utils.timezone.now)),
                ('horainicio_1', models.TimeField()),
                ('horafin_1', models.TimeField()),
                ('nota_1', models.IntegerField()),
                ('lugar_2', models.CharField(max_length=50)),
                ('campus_2', models.CharField(max_length=250)),
                ('espacio_2', models.CharField(max_length=250)),
                ('fechadefensa_2', models.DateField(default=django.utils.timezone.now)),
                ('horainicio_2', models.TimeField()),
                ('horafin_2', models.TimeField()),
                ('nota_2', models.IntegerField()),
                ('lugar_3', models.CharField(max_length=50)),
                ('campus_3', models.CharField(max_length=250)),
                ('espacio_3', models.CharField(max_length=250)),
                ('fechadefensa_3', models.DateField(default=django.utils.timezone.now)),
                ('horainicio_3', models.TimeField()),
                ('horafin_3', models.TimeField()),
                ('nota_3', models.IntegerField()),
                ('docrespaldo', models.FileField(blank=True, null=True, upload_to='documento/perfil', verbose_name='Agregar Documentación')),
                ('notatotal', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actagrado_area', to='seg_mod_graduacion.area', verbose_name='Seleccione el Area')),
                ('area_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actagrado_area_1', to='seg_mod_graduacion.area', verbose_name='Seleccione el Area')),
                ('area_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actagrado_area_2', to='seg_mod_graduacion.area', verbose_name='Seleccione el Area')),
                ('area_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actagrado_area_3', to='seg_mod_graduacion.area', verbose_name='Seleccione el Area')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.carrera')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_grado_estudiante', to=settings.AUTH_USER_MODEL)),
                ('jurado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_grado_jurado_1', to=settings.AUTH_USER_MODEL)),
                ('jurado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_grado_jurado_2', to=settings.AUTH_USER_MODEL)),
                ('jurado_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_grado_jurado_3', to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad')),
                ('perperiodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.periodo')),
                ('presidenteacta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_grado_presidente_Asi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acta Grado',
                'verbose_name_plural': 'Actas de Grado',
            },
        ),
    ]
