# Generated by Django 5.1 on 2024-10-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0017_actagrado_fecha_alter_actagrado_fechadefensa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actagrado',
            name='campus',
            field=models.CharField(default='Campus Universitario Hernán Melgar Justiniano.', max_length=250),
        ),
        migrations.AlterField(
            model_name='actagrado',
            name='campus_1',
            field=models.CharField(default='Campus Universitario Hernán Melgar Justiniano.', max_length=250),
        ),
        migrations.AlterField(
            model_name='actagrado',
            name='campus_2',
            field=models.CharField(default='Campus Universitario Hernán Melgar Justiniano.', max_length=250),
        ),
        migrations.AlterField(
            model_name='actagrado',
            name='campus_3',
            field=models.CharField(default='Campus Universitario Hernán Melgar Justiniano.', max_length=250),
        ),
    ]
