# Generated by Django 5.1 on 2024-10-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0018_alter_actagrado_campus_alter_actagrado_campus_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='carrera',
        ),
    ]
